apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command:
    - sleep
    - infinity
    volumeMounts:
      - mountPath: /tmp
        name: cephfs
  volumes:
    - name: cephfs
      persistentVolumeClaim:
        claimName: cephfs-pvc