apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command:
    - sleep
    - infinity
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
    options:
      - name: ndots
        value: "2"
      - name: edns0