apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: ubuntu:20.04
    volumeMounts:
    - mountPath: /mount
      name: config
    command:
      - sleep
      - infinity
  volumes:
  - name: config
    configMap:
      name: test-params